### ISSUE TITLE
Does not work with sbt 0.13.9

### ISSUE THREAD

**Issue by SRGOM** [dscleaver/sbt-quickfix#19] opened 2015-09-02 10:04 UTC
QuickFixLogger gets initialized but errors/warnings are not handled.

**Comment by leifwickland** [comment] 2015-11-20 06:57
+1 
As near as I can tell the problem started in 0.13.8. It works for me in 0.13.7.
At least part of the problem is that the quickfix file isn't being written.

**Comment by zmre** [comment] 2016-02-12 19:46
+1

**Comment by brendanmaguire** [comment] 2016-05-19 14:13
Works for me with sbt 0.13.9 . Might not be the correct way to do it?

**Comment by adelbertc** [comment] 2016-06-12 08:09
Should be fixed by https://github.com/dscleaver/sbt-quickfix/pull/20

**Closed by adelbertc** 2016-06-12 08:09 UTC
